config/routes.rb
Rails.application.routes.draw do
  resources :product_orders
  resources :products
  resources :suppliers
  resources :users
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'welcome#index'
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_action :set_product_order, only: %i[ show edit update destroy ]

  # GET /product_orders or /product_orders.json
  def index
    @product_orders = ProductOrder.all
  end

  # GET /product_orders/1 or /product_orders/1.json
  def show
  end

  # GET /product_orders/new
  def new
    @product_order = ProductOrder.new
  end

  # GET /product_orders/1/edit
  def edit
  end

  # POST /product_orders or /product_orders.json
  def create
    @product_order = ProductOrder.new(product_order_params)

    respond_to do |format|
      if @product_order.save
        format.html { redirect_to product_order_url(@product_order), notice: "Product order was successfully created." }
        format.json { render :show, status: :created, location: @product_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_orders/1 or /product_orders/1.json
  def update
    respond_to do |format|
      if @product_order.update(product_order_params)
        format.html { redirect_to product_order_url(@product_order), notice: "Product order was successfully updated." }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_orders/1 or /product_orders/1.json
  def destroy
    @product_order.destroy!

    respond_to do |format|
      format.html { redirect_to product_orders_url, notice: "Product order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_order
      @product_order = ProductOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_order_params
      params.require(:product_order).permit(:user_id, :product_id, :quantity, :pallet, :description)
    end
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/views/product_orders/_form.html.erb
<%= form_with(model: product_order) do |form| %>
  <% if product_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_order.errors.count, "error") %> prohibited this product_order from being saved:</h2>

      <ul>
        <% product_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :pallet, style: "display: block" %>
    <%= form.text_field :pallet %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_orders/_product_order.html.erb
<div id="<%= dom_id product_order %>">
  <p>
    <strong>User:</strong>
    <%= product_order.user_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= product_order.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product_order.quantity %>
  </p>

  <p>
    <strong>Pallet:</strong>
    <%= product_order.pallet %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product_order.description %>
  </p>

</div>

app/views/product_orders/edit.html.erb
<h1>Editing product order</h1>

<%= render "form", product_order: @product_order %>

<br>

<div>
  <%= link_to "Show this product order", @product_order %> |
  <%= link_to "Back to product orders", product_orders_path %>
</div>

app/views/product_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product orders</h1>

<div id="product_orders">
  <% @product_orders.each do |product_order| %>
    <%= render product_order %>
    <p>
      <%= link_to "Show this product order", product_order %>
    </p>
  <% end %>
</div>

<%= link_to "New product order", new_product_order_path %>

app/views/product_orders/new.html.erb
<h1>New product order</h1>

<%= render "form", product_order: @product_order %>

<br>

<div>
  <%= link_to "Back to product orders", product_orders_path %>
</div>

app/views/product_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_order %>

<div>
  <%= link_to "Edit this product order", edit_product_order_path(@product_order) %> |
  <%= link_to "Back to product orders", product_orders_path %>

  <%= button_to "Destroy this product order", @product_order, method: :delete %>
</div>